"""

List of words:
I used ChatGPT to give me an example of words with minimum 6 letters and the maximum 9 letters.

"""

Words = [
    "rainbow",
    "elephant",
    "mountain",
    "necklace",
    "computer",
    "festival",
    "symphony",
    "universe",
    "language",
    "medicine",
    "champion",
    "paradise",
    "together",
    "brilliant",
    "homeless",
    "hospital",
    "bicycle",
    "umbrella",
    "location",
    "behavior",
    "couple",
    "private",
    "diamond",
    "journey",
    "library",
    "perfect",
    "compass",
    "harmony",
    "chicken",
    "mystery",
    "justice",
    "control",
    "weather",
    "lantern",
    "excited",
    "concert",
    "dolphin",
    "kitchen",
    "balance",
    "captain",
    "silence",
    "freedom",
    "genuine",
    "holiday",
    "inspire",
    "journey",
    "kingdom",
    "loyalty",
    "network",
    "airplane",
    "partners",
]
